package org.apache.derby.catalog;

/**
 <p>An interface for describing a default for a column or parameter in Derby systems.</p>
 这个接口用来描述在derby系统中列或者参数的默认信息.
 todo 这两者为什么要用同一个接口呢?
 */
public interface DefaultInfo
{
	/**
	 * Get the text of a default.
	 *
	 * @return The text of the default.
	 */
	public String getDefaultText();
	
	/**
	 * If this default is a generation clause, then return the names of
	 * other columns in the row which the generation clause references.
	 */
	public String[] getReferencedColumnNames();
	
	
	/**
	 * Is default value generated by auto increment?
	 *
	 * @return true if always generated by auto increment.
	 */
	
	//ToCleanUp
	//Additional definitive information of AutoIncremnt 
	//such as autoIncrementStart and autoInrementInc 
	//should be gotten from this interface.

	public boolean isDefaultValueAutoinc();//自增

	/**
	 * Return true if this is the generation clause for a generated column.
	 */
	public boolean isGeneratedColumn();
	
	/**
	 * Return the name of the current schema when the default was created. This
	 * is filled in for generated columns.
	 */
	public String   getOriginalCurrentSchema();
	

}
